### ISSUE TITLE
geom_vline requires converting to numeric when intercept is a POSIXct

### ISSUE THREAD

**Issue by stevencb** [hadley/ggplot2#1048]
Even though ggplot successfully plots points where the x-axis is a POSIXct, calling "geom_vline" with the x-intercept being set to the same x values gives the error "Error: Discrete value supplied to continuous scale".

It seems like a bug that the code below labeled "Does NOT work."  would produce this error.

This issue is similar but not the quite the same as other issues I have seen in "hadley / ggplot2".

Thanks,

library(dplyr)
library(ggplot2)

xdf <- data.frame(datetime = seq(as.POSIXct('2015-01-01 15:00:00'), length.out = 5, by = 'day'),
                  count = 1:5)
### Grab subset of xdf
ydf <- xdf %>% filter(count >= 3, count <= 4)

#########################################
#########################################
ggplot(xdf, aes(datetime, count)) +
  geom_point() +
  geom_vline(aes(xintercept = datetime))
# Error: Discrete value supplied to continuous scale

#########################################
#########################################
ggplot(xdf, aes(datetime, count)) +
  geom_point() +
  geom_vline(aes(xintercept = datetime), data = ydf)
# Error: Discrete value supplied to continuous scale

#########################################
#########################################
ggplot(xdf, aes(datetime, count)) +
  geom_point() +
  geom_vline(aes(xintercept = as.numeric(datetime)))
### Also works.
ggplot(xdf, aes(datetime, count)) +
  geom_point() +
  geom_vline(aes(xintercept = as.numeric(datetime)), data = ydf)

**Comment by hadley** [comment]
Yes, unfortunately this is a known issue that is difficult to fix.

**Comment by moritzphilipph** [comment]
I have a similar problem:

Fehler während wrapup: Objekt 'comments_raw' nicht gefunden

Fehler in ggplot(aes(datetime, weighted_sentiment), data = comments) : 
  Objekt 'comments' nicht gefunden

Could anybody help me pls.

**Comment by batpigandme** [comment]
Since this is a known and closed issue, this isn't the best place for you to get help. 

Your question is probably a better fit for https://community.rstudio.com. Do you mind asking it over there? You'll definitely want to make a [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample), since It will help others help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

Currently, the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```

If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste the contents into the forum.
```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```
