### ISSUE TITLE
Minimum number of points for boxplots

### ISSUE THREAD

**Issue by hhoeflin** [hadley/ggplot2#1094]
Here is an issue I have struggled with repeatedly. When using geom_boxplot, a boxplot is done, irrespective of the number of data points that are available. This is especially a problem when doing boxplots across various groups (e.g. timepoints) where not always the same number of samples is available. In plotting, all the boxplots look equivalent, although it can easily be the case that some are only based on 2-3 points (or even 1).

Therefore I have the following feature request: Add a parameter to geom_boxplot that requires a minimum number of points for the boxplot to be done. By default it can be set to 0 not to change current behavior. then
1. If minimum number of points reached - do the boxplot as usual
2. If minimum number of points not reached - plot the available data as points instead (with color being equal to the fill color of the boxplot).

Thanks!

P.S. The same argument is also true for geom_violin.
P.P.S. I guess the easiest way to implement this practically is to declare all data points "outliers" if there are less than the request minimum and set the outlier color to the fill color in this case.

**Comment by hadley** [comment]
I'd recommend doing this yourself with dplyr (or otherwise), e.g.

```{r}
library(dplyr)
mpg %>% group_by(cyl) %>% filter(n() > 5)
```

**Comment by davidaknowles** [comment]
I'm adding a plus one for this. The issue with pre-filtering as @hadley suggests is 
1) I'm usually putting geom_point on top of geom_boxplot so I would now need an unfiltered and filtered version of my data for the two geoms separately
2) If I have multiple groups then using position_dodge won't work because geom_boxplot doesn't know about the groups it needs to dodge that got filtered.
