### ISSUE TITLE
projections of world map seem buggy

### ISSUE THREAD

**Issue by arilamstein** [hadley/ggplot2#1104]
Applying projections to world maps via `coord_map()` seem to result in buggy images. I am using ggplot 1.0.1 on R 3.2.0.

```
world <- map_data("world")
worldmap <- ggplot(world, aes(x=long, y=lat, group=group)) +
  geom_path() +
  scale_y_continuous(breaks=(-2:2) * 30) +
  scale_x_continuous(breaks=(-4:4) * 45) 

worldmap + coord_map()
worldmap + coord_map("sinusoidal")  
worldmap + coord_map("cylindrical")  
````

![ggplot-mercator](https://cloud.githubusercontent.com/assets/50784/7580110/5b7cddb6-f823-11e4-8872-a022ca9ebe22.png)
![ggplot-cylindrical](https://cloud.githubusercontent.com/assets/50784/7580105/5752dc5e-f823-11e4-886d-e3bc0c1ec0e4.png)
![ggplot-cylindrical](https://cloud.githubusercontent.com/assets/50784/7580112/5fd1b7b0-f823-11e4-987a-b71cb278e028.png)

**Comment by arilamstein** [comment]
For reference, I first reported this on the ggplot2 mailing list: https://groups.google.com/forum/#!topic/ggplot2/eucbTNKAyYE

**Comment by hadley** [comment]
@hrbrmstr @andysouth do either of you know the right invocation in right to break the lines that go "behind" the globe?

**Comment by hrbrmstr** [comment]
Aye. I'll have time later today to show examples.

**Comment by hrbrmstr** [comment]
If you take a look at `range(world$long)` — which results in `c(-179.9572, 190.2908)` — the points > 180° cause issues with the polygon rendering. Just specify the `xlim` in `coord_map` and it won't distort the polygons. You do lose a bit on the edge (read further for a different solution).
 
    library(gridExtra)

    m1 <- worldmap + coord_map(xlim=c(-180,180))
    m2 <- worldmap + coord_map("sinusoidal", xlim=c(-180,180))  
    m3 <- worldmap + coord_map("cylindrical", xlim=c(-180,180)) 

    grid.arrange(m1, m2, m3, ncol=1)

![image](https://cloud.githubusercontent.com/assets/509878/8160833/b3acafc4-1340-11e5-84b8-9bdec974e779.png)

If you use a better map data source (and are willing to forsake Antarctica, which you really should unless you absolutely need it) you can use `rgdal` to read in Natural Earth maps like this one where `range(nat_map$long)` is sanely `c(-180, 180)`

    library(httr)
    library(R.utils)
    library(rgdal)

    GET("https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_50m_admin_0_countries.geojson.gz?raw=true",
        write_disk("world.gz"))
    gunzip("world.gz")

    nat <- readOGR("world", "OGRGeoJSON")
    nat_map <- fortify(nat)

    gg <- ggplot()
    gg <- gg + geom_map(data=nat_map, map=nat_map,
                        aes(x=long, y=lat, map_id=id))

    g1 <- gg + coord_map(ylim=c(-60, 80))
    g2 <- gg + coord_map("sinusoidal", ylim=c(-60, 80))
    g3 <- gg + coord_map("cylindrical", ylim=c(-60, 80))

    grid.arrange(g1, g2, g3, ncol=1)

![image](https://cloud.githubusercontent.com/assets/509878/8161553/ed14d084-1345-11e5-971b-2479d396c7dd.png)

(it's really mapproject that's causing the issues. values outside -180:180 or -80:80 cause it to produce `NA`'s IIRC)

Might I offer the use of at least `rectangular` for a world map (someone really needs to add Winkel Tripel to `mapproject` since I hate projecting first then `ggplot`ing:

    g + coord_map("rectangular", lat0=0, ylim=c(-60, 80))

![image](https://cloud.githubusercontent.com/assets/509878/8161650/79596244-1346-11e5-84b9-e4fa76c5b29b.png)

I realize you were probably just showing the other ones for example (i.e. the issue occurs across projections and it's easiest to show 0 parameter `mapproject` examples ;-))

**Comment by arilamstein** [comment]
@hrbrmstr Thanks for the thorough answer. Is there any legitimate reason for a map to have longitude outside of (-180, 180)? Does it make sense for ggplot2 to emit a warning in this case?

**Comment by hrbrmstr** [comment]
(being verbose for Google & posterity)

On Earth, latitude measurements range from 90°N, to zero at the equator, to 90°S. Longitude expresses the distance of a point east or west, relative to the Prime meridian which has a longitude of 0°. Places located east of Prime may have longitude angles up to 180°E; places located west of Prime may have longitudes up to 180°W.

That's a long way of saying `latitude <- c(-90, 90)` & `longitude <- c(-180, 180)`.

In theory, `coord_map` _could_ do what you're saying. Even the lat/long cartographic coordinate systems on other planets (which `ggplot` can plot!). So at least tossing a warning might be in order (again, in `coord_map`). 

Interestingly enough, when I take a look at the [source data](https://www.evl.uic.edu/pape/data/WDB/) for the `maps` package (which is ultimately what `map_data` is using) their latitude range is `c(-85.47028 ,83.62361)` and their longitude range is `c(-544.0886, 180.0000)` which leads me to believe some of the original data was in 0-360° measurements (at least for longitude). There are actually 1,843 instances when the longitude value dips below 180. All those errors seem to be in `asia-cil.txt` in the original data. None of that explains how the converted data into R has the values it does.

Even `world2` (another base R map source) has:

    w2 <- map("world2", plot=FALSE)
    range(w2$x, na.rm=TRUE)
    
    ## [1]  -5.072266 369.988892

Which is clearly outside the _"This map is based on latitudes [0, 360)"_ in the package manual.

@hadley is there some r-project lore that might explain some of this?

**Comment by hadley** [comment]
@hrbrmstr I think the maps package came from old S-plus code. I'd rather find better modern sources of data than try and work around problems in the maps package.

**Comment by hrbrmstr** [comment]
Agreed (hence my willingness to work on `naturalearth`).

**Comment by hadley** [comment]
I'm going to close this and we'll work on better data sources elsewhere
