### ISSUE TITLE
Some characters in boxplot values cause problems

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1150]
This is based on one of the examples from `aes_position`:

```R
# This is OK
dat <- data.frame(a=1, b=2, c=3, d=4, e=5)
ggplot(dat, aes(x = 1, ymin = a, lower = b, middle = c, upper = d, ymax = e)) +
  geom_boxplot(stat = "identity")

# Error
dat <- data.frame(a=1, "25%"=2, c=3, d=4, e=5)
ggplot(dat, aes(x = 1, ymin = a, lower = "25%", middle = c, upper = d, ymax = e)) +
  geom_boxplot(stat = "identity")
# Error in Ops.factor(x, from[1]) : 
#   (converted from warning) ‘-’ not meaningful for factors
```

Perhaps there was some change in plyr that caused this? At the very least the examples should be fixed.

**Comment by BrianDiggs** [comment]
I see two different issues for the example giving the error:

First, the names in `dat` are not as they appear.

```r
> dat <- data.frame(a=1, "25%"=2, c=3, d=4, e=5)
> names(dat)
[1] "a"    "X25." "c"    "d"    "e"  
```

So there is no column named "25%" when you get to the `ggplot` call. This can be fixed with

```r
> dat <- data.frame(a=1, "25%"=2, c=3, d=4, e=5, check.names = FALSE)
> names(dat)
[1] "a"   "25%" "c"   "d"   "e" 
```

The second issue is with the quoting of the name. Even with the above fix you get

```r
> dat <- data.frame(a=1, "25%"=2, c=3, d=4, e=5, check.names = FALSE)
> ggplot(dat, aes(x = 1, ymin = a, lower = "25%", middle = c, upper = d, ymax = e)) +
+   geom_boxplot(stat = "identity")
Warning messages:
1: In Ops.factor(x, from[1]) : ‘-’ not meaningful for factors
2: In Ops.factor(x, from[1]) : ‘-’ not meaningful for factors
``` 

This is a context where a string literal is not cast as a name automatically, so the backtick escaping version of non-standard names must be used.

```r
dat <- data.frame(a=1, "25%"=2, c=3, d=4, e=5, check.names = FALSE)
ggplot(dat, aes(x = 1, ymin = a, lower = `25%`, middle = c, upper = d, ymax = e)) +
  geom_boxplot(stat = "identity")
```

I don't see how a change in `plyr` could have changed this; the name `"25%"` in `dat` would always have been changed to `"X25."`.

----

Looking back at the actual example in `aes_position`, it is

```r
library(plyr)
abc <- adply(matrix(rnorm(100), ncol = 5), 2, quantile, c(0, .25, .5, .75, 1))
b <- ggplot(abc, aes(x = X1, ymin = "0%", lower = "25%", middle = "50%", upper = "75%", ymax = "100%"))
b + geom_boxplot(stat = "identity")
```

The column names in `abc` are right

```r
> colnames(abc)
[1] "X1"   "0%"   "25%"  "50%"  "75%"  "100%"
```

so my first issue wasn't relevant. The second seems to have been a problem for awhile since similar errors are seen in http://docs.ggplot2.org/0.9.3.1/aes_position.html and http://docs.ggplot2.org/0.9.2/aes_position.html (versions 0.9.3.1 and 0.9.2). Using

```r
b <- ggplot(abc, aes(x = X1, ymin = `0%`, lower = `25%`, middle = `50%`, upper = `75%`, ymax = `100%`))
b + geom_boxplot(stat = "identity")
```

works, though.

**Comment by hadley** [comment]
@BrianDiggs' analysis looks good to me - I don't think this is a bug.

**Comment by BrianDiggs** [comment]
For completeness, noting that the example was removed in d323fb488e0813edbb40e430064097ca4a9bba2c
