### ISSUE TITLE
facet_grid(x ~ x) is plotting in the first column rather than the diagonal

### ISSUE THREAD

**Issue by wkostelecki** [hadley/ggplot2#1153]
example:
ggplot(data.frame(a = letters[1:3], y = rnorm(3))) + geom_point(aes(y, y)) + facet_grid(a~a)

**Comment by hadley** [comment]
The problem is that internally `facet_grid` creates a data frame that has one column for each facetting variable, and then you end up with two columns called `a`, which causes problems down the road. This is pretty deep in the facetting code, and a pretty pathological example, so unfortunately it's not going to get fixed.
