### ISSUE TITLE
`annotation_raster` isn't working when data is not specified in the base layer?

### ISSUE THREAD

**Issue by w9** [hadley/ggplot2#1164]
Refer to: http://stackoverflow.com/questions/31396095/why-doesnt-annotation-raster-work?noredirect=1#comment50768233_31396095

The question is copied as below:

----------------------

In the documentation, there's one example showing the usage of `annotation_raster` as below.

    ggplot(aes(x=mpg, y=wt), data=mtcars) +
      annotation_raster('red', -Inf, Inf, -Inf, Inf) +
      geom_point()

This works fine, however, when I move the data and aes into the layer, suddenly it doesn't work anymore:

    ggplot() +
      annotation_raster('red', -Inf, Inf, -Inf, Inf) +
      geom_point(aes(x=mpg, y=wt), data=mtcars)  # doesn't work

This is perplexing because to me these two seem semantically identical.

Is there a reason why the second line won't work and is there a way to use `annotation_raster` without specifying data and aes early in the base layer?

**Comment by BrianDiggs** [comment]
I think this may be a bug and not just the odd quirk that sometimes happens when the first layer has data which is different in type than the rest of the data.

It's worth noting that "doesn't work" means that the points are plotted, but there is no red block/annotation behind them.

Here are two more examples which make me think the problem is related to `annotation_raster`:

```r
ggplot() +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf, fill="red") +
  geom_point(aes(x=mpg, y=wt), data=mtcars)  # works
```

This one has no data/aes in the original call and an annotation as the first layer but it does work.

```r
ggplot() +
  annotation_raster('red', 20, 25, 3, 4) +
  geom_point(aes(x=mpg, y=wt), data=mtcars)  # doesn't work
```

This one does not use infinite extents but does not work. That indicates it is not just a simple stretching/training issue.

**Comment by hadley** [comment]
This is by design - annotation_raster don't affect the scales of the plot, so you need to specify some base data and aesthetics.
