### ISSUE TITLE
coord_trans() bug causes empty plot

### ISSUE THREAD

**Issue by sumtxt** [hadley/ggplot2#1168]
If a variable contains zeros and the coordinate system is transformed to log space, the plot remains empty of data points and and the axis fails to render. 

Example:
diamonds$price[1] <- 0
qplot(carat, price, data=diamonds) + coord_trans(x = "log10", y = "log10")

**Comment by hadley** [comment]
This is basically the same problem as #980 - and I can't see any easy way to fix it here.  The problem is that the ranges are computed on the untransformed data, and then transformed. To avoid the problem, you'd need to transform and the compute the ranges. But that would require some really big changes, and it doesn't seem worth given the rarity of the problem.
