### ISSUE TITLE
Layer$new should not take strings for stat, geom, or position

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1177]
For example, `stat="identity"` should be replaced with `stat=StatIdentity`, and similar for position: https://github.com/hadley/ggplot2/blob/efddff6/R/annotation-custom.r#L47-L56

**Comment by BrianDiggs** [comment]
Would `Geom` and `Stat` (or, really, the individual geoms and stats) still take strings for these arguments, promoting them before calling `Layer$new`, or would this change echo through to those arguments? Because if the `stat`/`geom`/`position` arguments everywhere can no longer be strings, that will break *a lot* of code out there.

**Comment by wch** [comment]
Oh, good point. Maybe it should just be changed in the internal calls to `Layer$new`, but that function should still accept strings.

**Comment by hadley** [comment]
I think we should just change it in the internal calls to `Layer$new()`.

**Comment by hadley** [comment]
Now in #1173
