### ISSUE TITLE
integer type has "continuous values" according to scale_color_discrete.

### ISSUE THREAD

**Issue by jmccreight** [hadley/ggplot2#1340]
This minimal reproducible example builds on that of the [similar bug for scale_shape_identity](https://github.com/hadley/ggplot2/issues/402#issuecomment-139673899) which was previously resolved (so the example may seem more than minimal, but I'm referencing a precedent bug with a solution - why I also commented there)
```{r}
R version 3.2.2 (2015-08-14) -- "Fire Safety"
library(ggplot2)
df2 <- data.frame(x = 1:5 , y = 1:25, z = 1:25)
s <- ggplot(df2, aes(x = x, y = y))
s + geom_point(aes(shape = z), size = 4) + scale_shape_identity()
s + geom_point(aes(shape = z, color=z), size = 4) + scale_shape_identity() + scale_color_discrete() 
# Error: Continuous value supplied to discrete scale
```
Note there's no error for scale_shape_identity. But there is for scale_color_discrete. Integer is a discrete variable, not a continuous variable, which creates cognitive dissonance for the person trying to interpret this error. Seems like integer type should be treated like an ordered factor, but that may not be the best solution internally... 
Thanks!

**Comment by wch** [comment]
This is tricky because in many (most?) cases, integer values passed to ggplot actually do represent continuous values -- integer values are *granular*, but in many cases they belong on a continuous scale. In the example above, `x` is a continuous scale, even though integer values are used.

ggplot2 treats integer and numeric values as continuous, and it treats factors and characters as discrete (categorical).

A workaround is to use `factor(z)` to explicitly create discrete data:

```R
s + geom_point(aes(shape = z, color= factor(z)), size = 4) +
  scale_shape_identity() +
  scale_color_discrete() 
```
