### ISSUE TITLE
Pipe operator into ggsave and argument order

### ISSUE THREAD

**Issue by andygarcia** [hadley/ggplot2#1370]
`ggsave` currently takes the `plot` argument as the second argument of the function.

I would like to be able to use the `%>%` forward pipe operator to move from a dplyr+ggplot chain into ggsave as opposed to creating a temporary named object or just let the plot render in the background to be accessed via lastplot() (note this creates a Rplots.pdf) if run via RScript which is an annoyance)

Ideally the plot argument would be first, the `file` second to make use of the pipe

**Comment by hadley** [comment]
I considered doing this, but ultimately decided it was likely to break too much existing code. I wish we could though :/

**Comment by andygarcia** [comment]
Makes sense, perhaps a simple wrapper function will be my solution.

**Comment by BrianDiggs** [comment]
If you specify the file name in the `ggsave` call as a named argument, you don't even need a wrapper function. 

```r
library("ggplot2")
library("dplyr")

(ggplot(mtcars, aes(wt, mpg)) + geom_point()) %>%
    ggsave(filename="tmp.pdf")
```
This takes advantage of how R assigns passed parameters to formal parameters. Named parameters are assigned first, and then unnamed ones are assigned in order to what is left. Since you have already specified `filename`, the next available parameter is `plot`.

This won't work if you want to use the default naming algorithm, though.
