### ISSUE TITLE
discrete_scale( ... drop=TRUE) does not drop unused levels

### ISSUE THREAD

**Issue by chrisjcameron** [hadley/ggplot2#1433]
This could be a documentation issue, but drop=TRUE does not remove the unused levels from the legend. It would be nice to specify drop=TRUE instead of specifying both limits and breaks arguments,  especially because breaks=unique(dataframe$factor_var) is not particularly flexible. 

If the drop argument is meant to accomplish something else, documentation could be clarified.

    #require(stats)
    #require(methods)
    #require(graphics)
    #require(grDevices)
    #require(methods)
    #require(datasets)
    #require(utils)
    require(dplyr)
    require(ggplot2)

    dataframe = data.frame( x=c(0,1,0,1,0,1), y=c(0,1,1,2,2,3), f=as.factor(c(1,1,2,2,3,3)) )

    # Plot with all levels
    ( ggplot(dataframe, aes(x=x, y=y, group=f))
        + geom_line(size=.5, aes(color=f))
    )

    # Plot examining 2 levels
    #  keep factor-->color mapping the same between plots
    #  but also list only relevant levels in the legend
    #  define color using limits and breaks (brittle code)
    filtered_df = dataframe %>% filter(f %in% c('2','3'))
    ( ggplot(filtered_df, aes(x=x, y=y, group=f))
        + geom_line(size=.5, aes(color=f))
        + scale_colour_hue(limits=levels(filtered_df$f), breaks=unique(filtered_df$f))
    )

    # Perhaps there is an easier and more flexible way?
    # # Would be nice to avoid typing 'filtered_df' 2-3 times
    # DOES NOT WORK: Includes dropped group in legend
    ( ggplot(filtered_df, aes(x=x, y=y, group=f))
        + geom_line(size=.5, aes(color=f))
        + scale_colour_hue(limits=levels(filtered_df$f), drop=TRUE)
    )

**Comment by has2k1** [comment]
Same grievance as #1418.

Consider this approach instead
```R
filtered_df = dataframe %>% filter(f %in% c('2','3'))
filtered_df = factor(filtered_df)
( ggplot(filtered_df, aes(x=x, y=y, group=f))
  + geom_line(size=.5, aes(color=f))
  + scale_colour_hue()
)
```

**Comment by chrisjcameron** [comment]
@has2k1: Unfortunately, this suggested workaround does not work. It generates an error and does not retain the same level-->color mapping as the plot with all the levels.

From #1418 it seems that `limits` currently overrides `drop`.

Is it possible that when color is a factor, that a sensible automatic behavior would be to use the levels of the factor instead of the unique values of the factor and to respect the drop=TRUE argument? This would  make multiple plots generated with the same color factor automatically use the same color scheme and could be very convenient for multi-site comparisons.

**Comment by hadley** [comment]
@chrisjcameron can you please provide a _minimal_ reproducible example?

**Comment by chrisjcameron** [comment]
@hadley thanks for taking a look at this. Your packages are amazing and this is minor quibble compared to the overall productivity enhancements your packages support. 

The code example above is entirely self contained, replicates the issue consistently and is at least very close to minimal. To clarify the difference between the current behavior and the behavior I was expecting, I generated the plots and included them below. The basic idea is that I have data for multiple groups, identified by a factor and I wanted it to be easier to maintain the color associated with each level of the factor even if some plots don't use use data from all the groups. 

In the first plot below, there is a line for groups 1, 2 and 3. The colors are automatically assigned and look great. If we subset the dataset to include just 2 of the 3 groups and plot it again, we get a different color palette (as in the last image). 

![colors_all](https://cloud.githubusercontent.com/assets/1383080/12584823/5e50e2f6-c417-11e5-8ba6-5df4499c3d24.png)

Generating a plot on the subset that retains the same colors as the full plot involves defining a color scale and hard coding the limits and breaks in terms of the levels and unique values of the grouping factor. 

    + scale_colour_hue(limits=levels(filtered_df$f), breaks=unique(filtered_df$f))

![colors_2_hc](https://cloud.githubusercontent.com/assets/1383080/12584831/65a846ca-c417-11e5-9389-ce83fd7a764b.png)

My specific issue is that these two specifications are not equivalent and that seems like something that could be addressed in the documentation.

    + scale_colour_hue(limits=levels(filtered_df$f), drop=TRUE)
    + scale_colour_hue(limits=levels(filtered_df$f), breaks=unique(filtered_df$f))

The larger issue is that colors specified in terms of a factor level use the **unique values of the factor vector** rather than the **levels of the factor** to generate the color palette so the colors assigned to the levels of the factor are not automatically stable over different subsets of the same dataset. Ideally, one would be able to simply plot the subset using the same code that plots the full dataset and get consistent colors.

    filtered_df = dataframe %>% filter(f %in% c('2','3'))
    ( ggplot(filtered_df, aes(x=x, y=y, group=f))
        + ggtitle("2 groups, easy")
        + geom_line(size=.5, aes(color=f))
    )



@has2k1 suggested a possible work around, but the color pallet is not the same in these plots: 

![colors_2_fail](https://cloud.githubusercontent.com/assets/1383080/12584838/6abdb67c-c417-11e5-8104-2b1c5ee4dcb7.png)

**Comment by hadley** [comment]
It seems to me what you want is `drop = FALSE`:

```R
df <- data.frame(
  x = c(0,1,0,1,0,1), 
  y = c(0,1,1,2,2,3), 
  f = factor(c(1,1,2,2,3,3)) 
)

ggplot(df, aes(x, y, colour = f)) + 
  geom_line()

ggplot(subset(df, f != "1"), aes(x, y, colour = f)) + 
  geom_line() + 
  scale_colour_hue(drop = FALSE)
```

**Comment by xhdong-umd** [comment]
I have a different usage that want to keep the color mappings but remove the unused levels from legend guide. 

I'm building a shiny app that have some plots linked together interactively. And I need to keep color synced in different places.

<img width="672" alt="screen shot 2017-04-07 at 10 54 33 am" src="https://cloud.githubusercontent.com/assets/1730496/24805849/f5a840a6-1b80-11e7-8bdb-911ae67c4098.png">
<img width="634" alt="screen shot 2017-04-07 at 10 54 40 am" src="https://cloud.githubusercontent.com/assets/1730496/24805853/f88186f2-1b80-11e7-86f9-0df6914b3abf.png">
<img width="671" alt="screen shot 2017-04-07 at 10 54 45 am" src="https://cloud.githubusercontent.com/assets/25039897/24805885/17dbb4fa-1b81-11e7-8efd-a04e93bfb431.png">


There is a histogram to show the outliers of data, which I colored each bin in separate color, then draw a scatter plot with same color mapping. `drop=FALSE` can keep the color mapping easily. 

However because the distribution of histogram is not even, maybe only 5 bins in 20 bins have data. Then we will have 20 colors in legend of scatter plot. Right now I maintained the color mapping manually so the legend only showed the bins with data. If there could be an option to customize the legend then I can replace all may manual code with `drop = FALSE`.

<img width="659" alt="screen shot 2017-04-07 at 10 56 22 am" src="https://cloud.githubusercontent.com/assets/25039897/24805918/31e50cfc-1b81-11e7-9bfa-71ba861d6d87.png">
<img width="657" alt="screen shot 2017-04-07 at 10 56 27 am" src="https://cloud.githubusercontent.com/assets/25039897/24805923/372cf968-1b81-11e7-8efc-f130a6f6115a.png">

**Comment by hadley** [comment]
@xhdong-umd please file a minimal reproducible example as a new issue

**Comment by xhdong-umd** [comment]
@hadley I created new issue then I found the solution once I understood the `breaks` parameter in `discrete_scale` and knew it can be used in `scale_colour_hue`.
