### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by hammao** [hadley/ggplot2#1450]
Error in add_ggplot(e1, e2, e2name) : could not find function "is.coord"

**Comment by hadley** [comment]
Please provide a reproducible example

**Comment by gilleschapron** [comment]
Hi,
In any case, I had the same error when I used the ```ggtern``` package.
```ggtern``` overwrite a lot of ```ggplot2``` functions.
I believe so that the error cames from ```ggtern``` and not from ```ggplot2```.
I have no choice but stop using ```ggtern``` until a fix.

**Comment by yutannihilation** [comment]
This commit https://github.com/hadley/ggplot2/commit/1487e0100515312b4ff2777163d09fdaf4f86655 changed `is.coord()` to `is.Coord()`, while `ggtern` uses `is.coord()` here: https://github.com/nicholasehamilton/ggtern/blob/1801162a281240dcdc67760dcb41f67972c20f59/R/plot-construction.R#L37

I think you should file the issue to the package repo. But, for `ggtern`, I'm afraid there are little chance for the ggtern package to be fixed since the owner's account seems to be deleted...: https://github.com/nicholasehamilton

**Comment by hammao** [comment]
I was able to communicate with the owner   a week ago, I'll notify him. Thanks for your   support. 

-------------------------------------------
Amao Abduljamiu O.
PhD Candidate - Geology
Earth Sciences Department
King Fahd University of Petroleum and Minerals (KFUPM)
Dhahran, Saudi Arabia
 
P. O. Box 1723 KFUPM, Dhahran 31261 Saudi Arabia
Tel. office +966 3 860 1661
Mobile: +966 535467527
Skype: lakesido02
Email: amao@kfupm.edu.sa
Alt: lekisoft@gmail.com
--------------------------------------------

**Comment by hammao** [comment]
Thanks for your prompt response, Gilles thinks I should remove the ggtern package and it would work. I'm away from my system for now but will try that tomorrow. 

Thanks 

-------------------------------------------
Amao Abduljamiu O.
PhD Candidate - Geology
Earth Sciences Department
King Fahd University of Petroleum and Minerals (KFUPM)
Dhahran, Saudi Arabia
 
P. O. Box 1723 KFUPM, Dhahran 31261 Saudi Arabia
Tel. office +966 3 860 1661
Mobile: +966 535467527
Skype: lakesido02
Email: amao@kfupm.edu.sa
Alt: lekisoft@gmail.com
--------------------------------------------
