### ISSUE TITLE
Panel Grid Aesthetics Can't be Changed for theme_classic

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1555]
It has no effect for `theme_classic`

    ggplot(mtcars, aes(wt, mpg)) + geom_point() + theme_classic() + theme(panel.grid.major.y = element_line(colour = "pink", size = 4))

but it does work for the other themes

    ggplot(mtcars, aes(wt, mpg)) + geom_point() + theme_bw() + theme(panel.grid.major.y = element_line(colour = "pink", size = 4))

It also doesn't work for the grid lines perpendicular to the x-axis.

**Comment by Katiedaisey** [comment]
Since panel.grid.major.y inherits from panel.grid.major while the later has an element_blank class, it will not inherit the desired element_line. This can easily be confirmed via

`calc_element('panel.grid.major.y', theme_classic() + theme(panel.grid.major.y = element_line(colour = "pink", size = 4)), verbose = T)` 

This will happen whenever a new element inherits from a element that was declared blank in the base theme. For instance, adding tick marks only on x with theme_minimal also fails:

`ggplot(mtcars, aes(wt, mpg)) + geom_point() + theme_minimal() + theme(axis.tick.x = element_line(colour = "pink", size = 4))`

It seems these might actually not work in only three cases in which case I would suggest just updating the two themes, classic and minimal, by declaring the problem children.

    theme_classic2 <- function(base_size = 12, base_family = ""){
      theme_bw(base_size = base_size, base_family = base_family) %+replace%
        theme(
          panel.border     = element_blank(),
          axis.line        = element_line(colour = "black"),
          panel.grid.major = element_line(),
          panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          strip.background = element_rect(colour = "black", size = 0.5),
          legend.key       = element_blank()
        )
    }

    theme_minimal2 <- function(base_size = 12, base_family = "") {
      # Starts with theme_bw and then modify some parts
      theme_bw(base_size = base_size, base_family = base_family) %+replace%
        theme(
          legend.background = element_blank(),
          legend.key        = element_blank(),
          panel.background  = element_blank(),
          panel.border      = element_blank(),
          strip.background  = element_blank(),
          plot.background   = element_blank(),
          axis.ticks        = element_line(),
          axis.ticks.x     = element_blank(),
          axis.ticks.y     = element_blank(),
          axis.ticks.length = unit(0, "lines")
        )
    }

**Comment by hadley** [comment]
@Katiedaisey would you be interested in doing a PR to make those changes? I'd really appreciate it.

**Comment by Katiedaisey** [comment]
@hadley Sure. Just let me check those are indeed the only conflicts and I'll send you one tomorrow.
