### ISSUE TITLE
Can't read strip labels using facet_wrap with switch = "y"

### ISSUE THREAD

**Issue by TomHarrop** [hadley/ggplot2#1556]
Hi, using `switch = "y"` in `facet_wrap()` is giving me unreadable strip labels near the y-axis.
```
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_wrap(~class, switch = "y")
```
![plot](https://cloud.githubusercontent.com/assets/5971975/13285675/2bf89f0a-dafc-11e5-8011-70be922f5236.png)

I tried the current release (`ggplot2_2.0.0`) and dev version (`ggplot2_2.0.0.9001`).

Thanks!

**Comment by hadley** [comment]
@lionel- could you take a look please?

**Comment by smouksassi** [comment]
by default `facet_wrap` produce "x" facets.
Not sure this use makes sense but it seems there is warnings when we use `facet_grid` but not `facet_wrap`
```r
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_grid(~class,switch="y")
```
Warning message:
Cannot switch y axis strips as they do not exist

**Comment by lionel-** [comment]
@smouksassi That's because the meaning of `switch` is slightly different in grid and wrap facets. Wrap facets have only kind of labels and switch refers to where you want them displayed. But grid facets have two kinds of labels and switch refers to which of those should be swapped.

I'll look into the bug shortly.

**Comment by smouksassi** [comment]
I see thanks @lionel-  so this argument now working as it was intented to
