### ISSUE TITLE
geom_smooth parameters no longer available in qplot

### ISSUE THREAD

**Issue by salauer** [hadley/ggplot2#1612]
In the past, I was able to write the following code:

`qplot(data=dat, x=x_var, y=y_var, geom=c("point", "smooth"), se=FALSE, method="lm")`

But now that returns the error: "Error: Unknown parameters: se, method"

Of course it isn't too difficult to just add `+ geom_smooth(se=FALSE, method="lm")` but I guess I don't understand why it was taken out of qplot's functionality.

**Comment by thomasp85** [comment]
Related to #1585

**Comment by hadley** [comment]
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

(@thomasp85 - I think it's actually slightly different - that issue is to do with aesthetics where as this is parameters. i.e. in this case we should be able to automatically pull the parameters out of the aesthetics)

**Comment by salauer** [comment]
Just tried this again after a long while and there appears to be no issue. Either "thanks ggplot team!" for fixing it or "sorry ggplot team!" if there was no issue in the first place.
Cheers
