### ISSUE TITLE
Design query - connectograms

### ISSUE THREAD

**Issue by richardbeare** [hadley/ggplot2#1615]
Hello,
I'm exploring designs for connectogram plots. ggbio does the right kind of thing but is tightly bound to the various bioconductor structures. I'd like to implement the same kind of capabilities for more general data. I've seen some discussion about connectograms and polar plots, but the results are not as nice.

The ggbio approach has functions that transform the data and then returns calls to the various geoms. This approach means that the geoms have access to the circular versions of the data and can figure out the scales, but it doesn't seem to be nice from the ggplot design point of view.

However, as it is necessary to transform the data to draw the circular segments, it seems difficult to fit the concept into a geom. I've done some experiments, but the problem is the axes are derived from the original data. I can see that there may be an avenue via adding a coordinate transform, but thought I'd make this query to see if you have any advice or know of similar examples.

Thanks

**Comment by thomasp85** [comment]
The [ggforce](https://github.com/thomasp85/ggforce) extension package does not currently implement this but has it in mind. It currently implements a range of circular gems that do not rely an a coordinate transform. The missing piece for connectograms is a `geom_wedge` but this is mainly due to time constraints atm. I suggest you raise an issue there as it is unlikely that this will be implemented directly in ggplot2

**Comment by richardbeare** [comment]
Thanks,
I have done a bunch of work on connectograms using ggplot infrastructure,
but I suspect the results break the rules a lot. I can send some examples
through shortly to see if they work for you. I'll check out ggforce
