### ISSUE TITLE
How can I axis.ticks while using theme_minimal()?

### ISSUE THREAD

**Issue by kfeng123** [hadley/ggplot2#1616]
once I use the theme_minimal(), the axis.ticks disappear. The theme_minimal() fit me well except the absense of axis.ticks . It doesn't work even if I use 

theme(axis.ticks=element_line(colour="black",size=2,linetype="dotted",lineend="round"))

How to solve?

**Comment by ptoche** [comment]
``axis.ticks.x`` works.

        library("ggplot2")
        ggplot(mtcars, aes(mpg, disp, color = factor(carb))) + geom_point(size = 3) + labs(title = "Scatter Plot") + theme_minimal() + theme(axis.ticks.x = element_line(size = 1, colour = "red"), axis.ticks.length = unit(14, "pt"))

**Comment by ptoche** [comment]
I'm not sure if ``axis.ticks.x`` and ``axis.ticks.y`` are supposed to inherit ``axis-ticks`` or whether you are supposed to act from the bottom up on them directly. If you're going to make changes to a theme, why not create your own. Very easy once you copy-paste from a theme you like. The following is a theme I'm currently experimenting on. You can take it and modify the bits to your liking. Then you just have to call ``theme_kfeng123()`` (or whatever you choose to call it, right now it's called ``theme_test``)  instead of ``theme_minimal()``.  http://pastebin.com/MFtJqMr8
