### ISSUE TITLE
geom_dotplot extends past axis

### ISSUE THREAD

**Issue by noamross** [hadley/ggplot2#1619]
When there are a large number of values, `geom_dotplot` extends beyond the range of the Y axis.  This isn't alleviated by changing the y axis limits.

```
library(ggplot2)
n = 350
quantiles = qnorm(seq(0, 1, length.out = n))
quantiles = data.frame(q = quantiles[-c(1, length(quantiles))])
ggplot(quantiles, aes(x=q)) + geom_dotplot(binwidth=bw) +
  scale_y_continuous(limits=c(0,1))
```

![screen shot 2016-04-21 at 12 49 45 pm](https://cloud.githubusercontent.com/assets/571752/14717467/9f1dbe62-07bf-11e6-9567-c057b2bd8113.png)

**Comment by wch** [comment]
I don't think there's a way to change this behavior and preserve other semantics of a dot plot. Do you have a suggestion of how one would do this?

**Comment by noamross** [comment]
Not yet, but I'll take a closer look an the internals this weekend.

**Comment by wch** [comment]
I wouldn't worry about the implementation details yet... I think the problem is at the conceptual level: what would you want it to do?

The only thing I can think of right now is to do something like have a smaller value for `stackratio`, to make the dots to overlap vertically. It might be possible to modify the grob to automatically squish the dots together when there's not enough vertical space, but it would be tricky to get it right.

**Comment by has2k1** [comment]
The problem is that, to have circular dots, the `binwidth` also "determines" the height of the dots through the `width:height` of the plot. That imposes a limit on the `binwidth`. The solution is to change the size dimensions of the plot.

**Comment by joey711** [comment]
In this combination of parameters one would want the vertical axis to be redundant with the number of dots stacked. Then the y-axis would not be meaningless (just redundant) and the limits/scaling would have some assurances of showing all the data.

I was just working through a pretty small/simple example where the dots ran off the top of the chart. It's a wonderful use-case for this geom category. It's a shame that it isn't really supported in the way most other ggplot2 geoms are.
