### ISSUE TITLE
data used in geom_text with geom specific aes is longer than it should be?

### ISSUE THREAD

**Issue by janschulz** [hadley/ggplot2#1626]
The following code is should print a label once, but it seems that it prints the label as many times as the original passed in data.frame was long.

```R
data = data.frame(x=seq(1:400))

library("ggplot2")
temp <- paste("Deuterium~D", "[", "alpha", "]")

p <- ggplot( data=data) +
  geom_text(aes( 656, 0.5, label = temp), parse=TRUE)
p  + coord_cartesian(xlim=c(0,4000), ylim=c(0.0,1.0)) 
p
#ggsave("test.svg")
```

When looking at the SVG file, it seems that the label is printed a lot of times. 

Not sure if this is the intended outcome, I would argue that the geoms should only get data as big as geom specific data if all for that geom relevant aes are specified in the geom. But on the other hand i don't really know if specifying data directly in the aes and not in a new data.frame is supported by ggplot.

[Original bugreport, which took ages when plotting and crashed the browser due to a 53MB big SVG file is in https://github.com/IRkernel/IRkernel/issues/291]

**Comment by janschulz** [comment]
Note that specifying an empty data.frame in the geom also fixes the problem:

```R
p <- ggplot( data=data) +
  geom_text(aes( 656, 0.5, label = temp), data=data.frame(), parse=TRUE)
p  + coord_cartesian(xlim=c(0,4000), ylim=c(0.0,1.0)) 
p
```

**Comment by thomasp85** [comment]
I think this is expected behaviour. When defining data in the `ggplot` call this dataset will be used for all layers that do not bring their own dataset. This means that literal values in your `aes` call will be added to the global dataset, thus recycled to the length of the dataset...

**Comment by Nikolai-Hlubek** [comment]
If this is expected behaviour than I would strongly recommend updating the manual. 

I think annotate does not parse plotmath, so geom_text is the only way to display some mathematical formulas. And that geom_text duplicates a label which is entered without any other structure for each data layer is by no way clear from the examples.

**Comment by thomasp85** [comment]
`geom_text` behaves as any other geom. To expect it to behave more like `annotate` because they both deal with text is wrong. I'll look into adding parsing of plotmath to annotate (if it doesn't already).

In general geoms are linked to a data set. If you set a data set globally you should expect to turn it off for the geoms that do not use it - this is not unique to `geom_text`

**Comment by janschulz** [comment]
Currently the algo seems to be "Take original data.frame, add new columns with value (=all the same), throw away all other columns" -> the df, which ends up being drawn by the geom, is basically the same row times the length of the original dataframe. One could argue that all geoms should test for the case that the geom specific aes sets all needed values (= `unique(to_be_drawn_data)` is a single row and all values in there are from the geom specific aes) and "optimizes" it to only one drawn point/text. 

```R
data = data.frame(x=seq(1:400))
p <- ggplot( data=data) +  geom_point(aes( 656, 0.5))
p
ggsave("test.svg") # -> 400 points written in the svg
```

Or warn in that case (unique(data) has only one row, all data from geom specific aes but length of data is "big"), that this is likely a user error which could lead to performance problems.

**Comment by hadley** [comment]
@janschulz if you want that behaviour, use `annotate()`.  For points/texts, the rule is one element per row in the data.
