### ISSUE TITLE
Discrete x/y scales reserve space for unused limits

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1638]
For example, from the [docs](http://docs.ggplot2.org/current/scale_discrete.html)

```
d <- ggplot(subset(diamonds, carat > 1), aes(cut, clarity)) +
      geom_jitter()
d + scale_x_discrete(limits=c("Fair","Ideal"))
```

![](http://docs.ggplot2.org/current/scale_discrete-11.png)

In the [0.9.3.1 docs](http://docs.ggplot2.org/0.9.3.1/scale_discrete.html), it looks like this:

![](http://docs.ggplot2.org/0.9.3.1/scale_discrete-17.png)

**Comment by wch** [comment]
I've bisected it to 89893c71ea575e198240e008ba2f42c9cbb7c6b7.

**Comment by hadley** [comment]
Probably related to  #1589

**Comment by thomasp85** [comment]
This is two unrelated problems. This one is easily fixed whereas #1589 is a bit less straightforward.

@hadley can you by chance remember what you tried to achieve in 89893c7? The message is that it improves the defaults, but since it is quite broken it is not obvious what was wrong with the old.

**Comment by hadley** [comment]
The goal was to fix #1542 - ie when you accidentally use a discrete scale with only continuous data. (You have to be able to use a mix of cont and disc so that jittering and similar work)

**Comment by thomasp85** [comment]
I somehow missed that reference - sorry 'bout that

**Comment by thomasp85** [comment]
It seems your change in `get_limits` didn't anticipate that the function was used in other places than `dimensions`.

Was the change supposed to do avoid drawing all breaks when numeric ranges were converted to discrete?

**Comment by hadley** [comment]
Your guess is as good as mine. (But I don't think it was supposed to)

**Comment by thomasp85** [comment]
Also is it intentional that continuous data on a discrete scale does not receives any expansion?

In general can you explain the calls to `expand_range`? It seems that the continuous range only receives additive expansion and discrete ranges only receives multiplicative expansion - shouldn't both receive both?

**Comment by hadley** [comment]
I'm not sure I can - I've done some exploration recently and I think multiplicative looks better for both. I don't remember my original reasoning

**Comment by thomasp85** [comment]
Makes sense - additive is very dependent on the number of levels. But no matter what looks best, shouldn't it honor what is passed in through the `expand` argument instead of just silently ignoring some of the settings?

**Comment by hadley** [comment]
The goal was always to get an aesthetic pleasing amount of space between the data and the axes. In an ideal world, that would be the same for both x and y axes, but there's no way to do that.

You're right that we should respect both options - I'm not sure why I made that change. 

For this problem, the fix is probably straightforward - what we need to make sure to capture is a few different motivating examples of mixing continuous and discrete values on a discrete axis.

**Comment by thomasp85** [comment]
I'll cook up a PR with a potential fix and let you stress test it as you seems to have a better idea about what is the intended functionality... (coding in the blind FTW :-)
