### ISSUE TITLE
Feature request: geom_ribbon: only fill area where ymax > ymin

### ISSUE THREAD

**Issue by emcapone** [hadley/ggplot2#1642]
In the aesthetics of geom_ribbon you specify a ymin and a ymax. However, geom_ribbon just fills the space between those two lines, without looking at minimum and maximum. [(related to my question on stackexchange)](http://stackoverflow.com/questions/37277729/ggplot2-fill-color-behaviour-of-geom-ribbon)

I propose that geom_point should only fill the area where ymax > ymin.

**Comment by jonocarroll** [comment]
As per my response on [stackoverflow](http://stackoverflow.com/a/37959052/4168169), this can be achieved using logic to assign `fill` within `aes(`.

```
## fill dependent on level > level2
h + 
  geom_ribbon(aes(ymin = level, ymax = level2, fill = level > level2)) +
  geom_line(aes(y = level)) + geom_line(aes(y = level2)) +
  scale_fill_manual(values = c("red", "green"), name = "fill")
```

<img src="http://i.stack.imgur.com/PCGCg.png"></img>

Voting to close #1642 as not necessary.

The lack of interpolated fill where no data exists is either a feature or a bug, I'm not sure.

**Comment by sschmitz** [comment]
I vote to reopen this FR. The solution presented by @jonocarroll unfortunately does not work in the general case.

What happens is that the result of the expression assigned to the `fill` aesthetic is coerced to a factor, and thus, by default, contributes to the `group` aesthetic. `geom_ribbon` thus draws two ribbons, one for each factor level. Here, the expression is `TRUE` for all years up to 1923, and `FALSE` afterwards. This also explains the interpolated fill issue: the `TRUE` group ends at 1923, and so does the ribbon, meaning the green area is cut off at 1923. As such, the "lack of interpolated fill" is neither a bug nor a feature here, but simply expected behavior of the group aesthetic. (In the year 1924 (and from 1965 on), `level` happens to be exactly equal to `level2`, so the red ribbon correctly starts at the intersection since this is not interpolated, but an actual data point. This is also the reason why @jonocarroll's [second SO solution](http://stackoverflow.com/a/37979793) works here, but also not in general.)

Let's use a crafted, less noisy example:
```R
d <- data.frame(x = 0:5, y = c(1, 1, -1, -1, -1, -1))

ggplot(d, aes(x = x, y = y)) +
  geom_area(aes(fill = y > 0)) +
  geom_line() + geom_line(y = 0)
```
![rplot01](https://cloud.githubusercontent.com/assets/4200058/17516782/b75631ee-5e40-11e6-96fa-dfdcc584425c.png)

This is the same situation as in the above dataset. Note that the expression for the `fill` aesthetic starts at one of its two factor levels, and at some point switches to the other one. It does not, however, switch back. If it does:
```R
d <- data.frame(x = 0:5, y = c(1, 1, -1, -1, 1, 1))

ggplot(d, aes(x = x, y = y)) +
  geom_area(aes(fill = y > 0)) +
  geom_line() + geom_line(y = 0)
```
![rplot02](https://cloud.githubusercontent.com/assets/4200058/17516892/569641b8-5e41-11e6-9fcf-56fde6d75b12.png)
Oops. Now both the left and the right side of the graph fall into the same group, while the middle part does not. The ribbon for the `TRUE` case, however, has no idea about the intermittent data, and just draws its ribbon across it.

From a user perspective, the easiest solution would probably be a `fill2` (or something) aesthetic for `geom_ribbon` which is applied wherever `ymax < ymin`, and defaults to `fill` (leading to the current behavior unless specified). I guess the interpolation is already done somewhere inside the `geom`, since we do have interpolated fill in the current, single-color behavior. Another possibility would be a stat that interpolates the intersection and provides a grouping variable which basically is the same as `ymax < ymin`, but with the intersection repeated for both groups.

**Comment by jonocarroll** [comment]
As per my SO answer, "I don't think this is a ggplot2 bug, I think this is expected behaviour."

You mention my solution of using two ribbons "works here, but also not in general" - what is wrong in general where this doesn't work?

**Comment by sschmitz** [comment]
As I understood it, the two-ribbon solution is supposed to fix the non-interpolating fill issue, and does so by specifying `level >= level2` for one ribbon, and `level <= level2` for the other one. The edge case `level == level2` is thus included in both ribbons. As I described, such a point exists in the SO dataset (in the year 1924) between the two regimes. My crafted data do not contain such a point, and thus, the approach fails:
```R
d <- data.frame(x = 0:5, y = c(1, 1, -1, -1, -1, -1))

ggplot() +
  geom_ribbon(data = d[d$y >= 0, ], aes(x = x, ymin = 0, ymax = y), fill = "green") +
  geom_ribbon(data = d[d$y <= 0, ], aes(x = x, ymin = 0, ymax = y), fill = "red") +
  geom_line(data = d, aes(x = x, y = y)) + geom_line(data = d, aes(x = x), y = 0)
```
![rplot03](https://cloud.githubusercontent.com/assets/4200058/17518719/53b1ff8e-5e49-11e6-93fd-c6d6454d292a.png)

It also exhibits the same problems for the second example:
```R
d <- data.frame(x = 0:5, y = c(1, 1, -1, -1, 1, 1))

ggplot() +
  geom_ribbon(data = d[d$y >= 0, ], aes(x = x, ymin = 0, ymax = y), fill = "green") +
  geom_ribbon(data = d[d$y <= 0, ], aes(x = x, ymin = 0, ymax = y), fill = "red") +
  geom_line(data = d, aes(x = x, y = y)) + geom_line(data = d, aes(x = x), y = 0)
```
![rplot04](https://cloud.githubusercontent.com/assets/4200058/17518772/7edec1ba-5e49-11e6-9f6b-520ec99ef06e.png)

**Comment by chamaoskurumi** [comment]
I second @sschmitz . I am also desperatly trying to find a solution for the case where there is no `level == level2` edge observation in the data. Solving this issue would allow me to plot beautiful revenue vs. spending line graphs with a ribbon visualising the balance.

**Comment by hadley** [comment]
I think this is better fixed outside of ggplot2 - you need some way to generate split a single ribbon into multiple polygons. If someone can implement an elegant algorithm to do so, I'd consider adding to ggplot2.

**Comment by hadley** [comment]
That said, I'm surprised that these generate two different plots:

```R
d <- data.frame(x = 0:5, y = c(1, 1, -1, -1, -1, -1))

ggplot(d, aes(x = x)) +
  geom_ribbon(aes(ymin = 0, ymax = y))

ggplot(d, aes(x = x)) +
  geom_area(aes(y = y))
```

**Comment by hadley** [comment]
Oh because `geom_area()` uses `position_stack()` which is going to cause problems here because we haven't cut up into multiple pieces (and `position_stack()` assumes bars, which don't have the same problem).
