### ISSUE TITLE
geom_point smallest point size is not in proportion

### ISSUE THREAD

**Issue by muranyia** [hadley/ggplot2#1666]
When visualizing a variable using point size, the smallest point size is sometimes significantly (not proportionally) smaller than the rest.
It seems that this occurs when the data has a categorical character (not class). Adding a little bit of jitter to the data normalizes the point sizes in the legend, but still not on the plot.

```Rscript
require(ggplot2)

# Test 1. Legend for 70 and corresponding point size on the graph are small.
ID <- c("C1", "C2", "C3", "C4", "C1", "C2", "C3", "C4", "C1", "C2", "C3", "C4", "C1", "C2", "C3", "C4")
CP <- c(70, 95, 100, NA, 70, 95, 100, NA, 70, 95, 100, NA, 70, 95, 100, NA)
variable <- c("A", "A", "A", "A", "B", "B", "B", "B", "C", "C", "C", "C", "D", "D", "D", "D")
value <- c(76, 20, 30, 17, 36, 10, 51, 41, 89, 1, 94, 6, 100, 98, 16, 33)
testdata <- data.frame(ID, CP, variable, value)
ggplot(data=testdata, aes(x=variable, y=value, group=ID, size=CP)) + geom_point()


# Test 2. Legend is good, point size for 70 on the graph is small.
ID <- c("C1", "C2", "C3", "C4", "C1", "C2", "C3", "C4", "C1", "C2", "C3", "C4", "C1", "C2", "C3", "C4")
CP <- c(71, 95, 97, NA, 71, 95, 97, NA, 71, 95, 97, NA, 71, 95, 97, NA) # "Jittered" a bit
variable <- c("A", "A", "A", "A", "B", "B", "B", "B", "C", "C", "C", "C", "D", "D", "D", "D")
value <- c(76, 20, 30, 17, 36, 10, 51, 41, 89, 1, 94, 6, 100, 98, 16, 33)
testdata <- data.frame(ID, CP, variable, value)
ggplot(data=testdata, aes(x=variable, y=value, group=ID, size=CP)) + geom_point()
```

**Comment by hadley** [comment]
I think this is just an artefact of human perception

```R
library(ggplot2)

df <- data.frame(
  a = 1,
  b = seq(70, 100, length = 10)
)

ggplot(df, aes(b, 1, size = b)) + 
  geom_point()
```

Maybe you want `scale_size_area()`?

```R
ggplot(df, aes(b, 1, size = b)) + 
  geom_point() +
  scale_size_area()
```

**Comment by muranyia** [comment]
Hi Hadley,

I'm having the same problem with your example. Please observe the legend on the attached graph.

![geom_point_test](https://cloud.githubusercontent.com/assets/7562080/17276201/0c0f91ba-5722-11e6-91c0-b1e9f8c9a437.png)

**Comment by wch** [comment]
@muranyia, I agree that there's something odd about the scaling. I generated almost the same plot with this, saved to PDF, and "measured" the diameters by overlaying small bars that are the same length as the diameter of the first dot.

If the diameter of the first dot (including the stroke) is 1, the second is  about 2, the third is ~2.25, the fourth is ~2.75, the fifth is ~3.1.


```R
library(ggplot2)

df <- data.frame(
  b = seq(100, 200, length = 10)
)
ggplot(df, aes(b, 1, size = b)) + 
  geom_point(alpha=0.3)
```

Here's the PDF with overlaid bars, for the first 5 points

[Rplot.pdf](https://github.com/hadley/ggplot2/files/392794/Rplot.pdf)

**Comment by thomasp85** [comment]
The scale behaves as it should, but it is visually "strange". To understand the behaviour we have to understand that with `scale_size_continuous` (the default scale) the domain is recalled between 0 and 1. This means that 70 becomes 0 and 100 becomes 1. In that sense the jump from 70 to 80 would seem bigger than the jump from 80 to 90 because the area increases many orders of magnitude between 70 and 80 while the area merely doubles between 80 and 90. The nominal increase is the same though:

```r
sizes <- seq(70, 100, length.out = 4)
scaledSizes <- scales::rescale(sizes)
scaledSizes <- scales::rescale(sqrt(scaledSizes), c(1, 6))
areas <- (scaledSizes/2) ^ 2 * pi
diff(areas)
# [1] 11.079483  8.423235  7.986217
```

The proportions are a bit off, which is due to the rescaling away from a zero base. Rescaling to 0-6 solves this, but is not the cause of the visual artefact:

```r
sizes <- seq(70, 100, length.out = 4)
scaledSizes <- scales::rescale(sizes)
scaledSizes <- scales::rescale(sqrt(scaledSizes), c(0,  6))
areas <- (scaledSizes/2) ^ 2 * pi
diff(areas)
# [1] 9.424778 9.424778 9.424778
```

It all goes back to 70 being the zero, which is confusing the brain. To avoid this and get a true zero use `scale_size_area` as suggested by @hadley 

We should maybe consider mapping to 0-6 instead of 1-6 as default for the areas based scales to get a true area proportionality?

**Comment by hadley** [comment]
It's also a little tricky now because the size of the point = size + stroke, so it's not a perfect scaling.

**Comment by thomasp85** [comment]
I think a lot could be alleviated by adding more than 4 breaks as this would give a smoother size transition around the beginning where the square root function changes the most...

**Comment by wch** [comment]
Ah, I think I was expecting the diameter/radius to be scaled linearly from the smallest to largest value, which I believe used to be the default. But now that requires `scale_radius()`. For a default scale, I think that `scale_radius(range=c(1, 6))` makes more sense as the current default, `scale_size(range=c(1, 6))`, despite its own drawbacks. (Obviously, `scale_size_area` is the best, but it can't be used in all cases.)

At any rate, if you guys disagree strongly with this, feel free to close.

**Comment by thomasp85** [comment]
I think the change happened in the v0.9-1.0 period as area is perceptually more linear. There are some problems with values that are not 0-based, as the above illustrates. Maybe it can be avoided by ignoring the bottom half of the square root transformation, that is, rescale the domain to 0.5-1.0 rather than 0-1 prior to the transformation. I'll look into it a bit so we can get better defaults

**Comment by steveharoz** [comment]
Is there a source showing that area is "perceptually more linear"? I'm not necessarily disagreeing :). It just goes against what the [Stevens Power](https://en.wikipedia.org/wiki/Stevens%27_power_law) measurements suggest.

Area has a scaling exponent of 0.7, whereas length has an exponent of 1. It's entirely likely that length is not the same as dot radius. That's why I'm looking for a source.

**Comment by thomasp85** [comment]
There is probably several. It is such a common point that I'll not bother to look it up right now :-)

Length is definitely a stronger mapping than area in cases where you can adjust length without disproportionally changing area. The "problem" with points is that the eye sees the area and not the diameter of the circle so if the scaling is not done in proportion to the area the points will lie to you with regards to their relative size encoding. I can see now that there are so many statements here that I'll need to back it up somehow. I'll go looking for a source :-)

**Comment by thomasp85** [comment]
Until I find one I'll invite you to play around with `scale_radius` and a fairly high range and see if you can convince yourself that this is indeed a bad representation of values :-)

**Comment by huftis** [comment]
@thomasp85 I found this paper, ‘Power Law Mapping In Human Area Perception’, that may be of interest: http://dx.doi.org/10.1142/S0129183111016397. Though I haven’t read it myself; it’s not an *open access* paper, unfortunately … :(

**Comment by hadley** [comment]
Maybe this should be the default range:

```R
df <- data.frame(
  a = 1,
  b = seq(70, 100, length = 10)
)

ggplot(df, aes(b, 1, size = b)) + 
  geom_point() + 
  scale_size(range = c(0, 6))
```

**Comment by hadley** [comment]
This is also useful to see exactly how the data is rescaled:

```R
plot(scales::area_pal())
```
![screen shot 2016-08-05 at 9 54 47 am](https://cloud.githubusercontent.com/assets/4196/17440548/a92a2c02-5af2-11e6-9eb6-16c390d1ade7.png)


Note that the data is rescaled to range 0-1 before this rescaling function sees it

**Comment by muranyia** [comment]
Thanks guys for taking the time and thinking so deeply about this. I know that changing the default could potentially mess up too many visualizations that are being used in the wild, so I think I'll be fine with using `scale_radius(range=c(1, 6))`.
