### ISSUE TITLE
Gap between stroke and point for large point

### ISSUE THREAD

**Issue by steveharoz** [hadley/ggplot2#1757]
Large points seem to disconnect from their stroke.  Also, a stroke size of 0 doesn't make it go away.

``` r
ggplot(data.frame(stroke = seq(0, 2, 0.5))) +
  geom_point(aes(x = stroke, y = 0, stroke = stroke, size = 15)) +
  scale_size_identity()
```
![image](https://cloud.githubusercontent.com/assets/2257540/18610091/2e03272e-7cd8-11e6-8098-6b4094e86f65.png)

Zoomed in: 
![image](https://cloud.githubusercontent.com/assets/2257540/18610113/e085f2e6-7cd8-11e6-9270-b3447ae9f20b.png)

I ran this on Windows 8.1 via both the Rstudio plot window and by calling `png()`. The problem goes away when rendered via `CairoWin()`

![image](https://cloud.githubusercontent.com/assets/2257540/18610102/b2dabaac-7cd8-11e6-9833-58c06e97cfd0.png)

**Comment by thomasp85** [comment]
My best guess is that it is a rounding problem in the device, since it only affects some devices. In any way this is not related to ggplot2 but further down the stack, either in grid or the device itself

**Comment by steveharoz** [comment]
@thomasp85 That makes sense. Is there any way in ggplot2 to completely disable the stroke? Setting `stroke = 0` doesn't seem to work.

**Comment by thomasp85** [comment]
What happens if you set it to `NA`

**Comment by steveharoz** [comment]
The points don't render at all. And there's no warning or error. 
![image](https://cloud.githubusercontent.com/assets/2257540/18610226/0bbf88ac-7cdc-11e6-9fbe-35b9d2668cbe.png)

**Comment by thomasp85** [comment]
Also if you set it outside of aes?

**Comment by steveharoz** [comment]
Yes. Here was the code for that:
``` r
ggplot(data.frame(stroke = seq(0, 2, 0.5))) +
  geom_point(aes(x = stroke, y = 0, size=15), stroke=NA) +
  scale_size_identity()
```

**Comment by thomasp85** [comment]
strange - pointsGrob works fine with `gpar(lwd = NA)`. I'm drawing a blank but maybe @hadley knows more

**Comment by wch** [comment]
This is due to a quirk in R's shapes. Shape 19 (which is now the default for `geom_point`) only respects `colour`, but whichever color is specified is used for both the fill and the stroke. If you want to have separate fill and stroke colors, you have to use shape 21 and set `fill` and `colour`. For example:

```R
ggplot(data.frame(x = seq(0, 2, 0.5)), aes(x = x, y = 0)) +
  geom_point(size=15, fill = "red", colour = "black", shape = 21) +
  scale_size_identity()
```

![image](https://cloud.githubusercontent.com/assets/86978/18610439/fe296c7a-7ce1-11e6-9b08-55ad0ac8de83.png)


ggplot2 used to use shape 16 as the default, which is even stranger in some ways, because it *only* has a fill (and no stroke), but this is controlled by `colour` -- `fill` is ignored.

```R
ggplot(data.frame(x = seq(0, 2, 0.5)), aes(x = x, y = 0)) +
  geom_point(size=15, fill = "red", colour = "black", shape = 16) +
  scale_size_identity()
```

![image](https://cloud.githubusercontent.com/assets/86978/18610446/2e025204-7ce2-11e6-8fde-fb5382c2a8a5.png)


Here it is with to ggplot2's current default shape ,19, whose fill and stroke is controlled by `colour`. I use `alpha=0.25` so that you can see that the stroke is separate from the fill:

```R
ggplot(data.frame(x = seq(0, 2, 0.5)), aes(x = x, y = 0)) +
  geom_point(size=15, fill = "red", colour = "black", shape = 19, alpha = 0.25) +
  scale_size_identity()
````

![image](https://cloud.githubusercontent.com/assets/86978/18610695/5f29d61c-7ce8-11e6-8ecd-16589ec2fb80.png)

As for why ggplot2 switched from 16 to 19: some graphics devices (like `cairo` and `X11`, I think) don't antialias fills, but they do antialias strokes. On these devices, the strokeless shape 16 looks terrible. Here's an example:

```R
ggplot(data.frame(x = seq(0, 2, 0.5)), aes(x = x, y = 0)) +
  geom_point(size=5, fill = "red", colour = "black", shape = 16) +
  scale_size_identity()
```

When I run it in R in a terminal window on my Linux machine, this is what it looks like:
![foo](https://cloud.githubusercontent.com/assets/86978/18610692/4dc09816-7ce8-11e6-94c0-757d001ca4c7.png)

**Comment by steveharoz** [comment]
Thanks @wch. The difference between shapes 16 and 19 make a lot more sense now. It still seems odd that rendering shapes 19 or 21 without a stroke causes either renders the stroke anyway (`stroke=0`) or doesn't render the whole shape (`stroke=NA`).

```
ggplot( data.frame(x=1:4, stroke=c(NA, 0:2)) ) +
    geom_point(aes(x=x, y=0, size=15, stroke=stroke), shape=21, fill='red') +
    scale_size_identity()
```
![image](https://cloud.githubusercontent.com/assets/2257540/18610816/ce00f3a6-7ceb-11e6-8999-eabe9139aee4.png)

**Comment by wch** [comment]
@steveharoz I agree, it's strange that using shape 21 with a stroke of 0 doesn't make the line disappear. It looks like with base R graphics, if you use shape 21 with `lwd=0` (stroke), it does make the stroke go away:

```R
plot(1:5, 1:5,
  pch = 21,       # shape
  bg = "red",     # fill color
  col = "black",  # stroke color
  cex = 5,        # diameter
  lwd = 0         # stroke width
)
```

![image](https://cloud.githubusercontent.com/assets/86978/18610878/0060c34c-7cee-11e6-83bc-15dd721fbcfd.png)

Also, using `lwd=NA` doesn't make the shape disappear -- instead it results in the default line width.


However, ggplot2 uses grid graphics, which is a layer of abstraction over base graphics, and it's possible that grid does something different. I think it would be worthwhile to open a new issue about this. :)

**Comment by steveharoz** [comment]
Thanks. Yeah, it looks like a grid big, not ggplot2.

**Comment by ssky2015** [comment]
maybe it relates to R and the monitor.It doesn't look good when plotting in R with a 1366X768 monitor. ggsave(dpi=) can save this.
