### ISSUE TITLE
Too many annotations on a plot causes an error

### ISSUE THREAD

**Issue by charlesmcbrearty** [hadley/ggplot2#1771]
The following snippet is causing R to error for me. 

```
library(ggplot2)
library(lubridate)

start.date <- as.Date('2014-1-1')

df <- data.frame(date=seq(start.date, start.date + days(1000), by="day"))
df$val <- 1:nrow(df)

plot <- qplot(df$date, df$val)

plot # this works fine.  Next statement causes the error

for(date in df$date) {
  date <- as.Date(date, origin = '1970-1-1')
  plot <- plot + annotate("rect", xmin=date, xmax=date + days(1), ymin=-Inf, ymax=Inf, alpha=0.2, fill="black")
}
```

This gives me the following error

Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?

I am using R 3.3.1, RStudio 0.99.1290, and ggplot2 2.1.0 on a 64-bit linux machine.  Please let me know if you need any other information to reproduce!

**Comment by thomasp85** [comment]
I don't know whether this is a toy-example or something you need, but there is no need for the loop:

```r
plot <- plot + annotate("rect", xmin=df$date, xmax=df$date + days(1), ymin=-Inf, ymax=Inf, alpha=0.2, fill="black")
```
 works fine...

As for the error I simply think it is because you're adding 1000(!) annotation layers - you can change the maximum number of nested calls using `options(expressions=)` but you really should be questioning your approach at this point as that many layers are going to affect performance no matter if it works or not...
