### ISSUE TITLE
Line weights/colors don't look right with theme_bw() and facets

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1786]
The panels have a bit of a raised, 3-D look to them. Also, the thinner/lighter lines on the left side look a bit off when the facet label box has a darker/heavier line.

```R
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  facet_grid(am ~ cyl) +
  theme_bw()
```

![image](https://cloud.githubusercontent.com/assets/86978/18890061/55184728-84c5-11e6-914c-bbaf132310b0.png)

**Comment by hadley** [comment]
@jiho @thomasp85 any ideas?  Did clipping change?

**Comment by thomasp85** [comment]
clipping might have changed, but I'm unable to reproduce the look on my computer... I'll go through the old clipping specs and see if I can find anything. but I might need you to verify...

**Comment by wch** [comment]
This is on my Ubuntu machine.

**Comment by thomasp85** [comment]
Can you check with the CRAN version and see if the look is ok there?

**Comment by wch** [comment]
Hm, it looks different depending on the R version and graphics device. This is probably too much information, but here you go. For each of the code snippets, I'll include two screenshots: one for ggplot2 2.1.0 and one for the latest dev version, 2.1.0.9000 (1ee809a).


## Calling `png()` in a terminal

```R
p <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  facet_grid(am ~ cyl) +
  theme_bw()

# Using default png() settings
png('test-terminal.png', width = 600, height = 400)
print(p)
dev.off()
```
![test-terminal](https://cloud.githubusercontent.com/assets/86978/18890476/fa99b924-84c6-11e6-9694-b02993584f74.png)

![test-terminal](https://cloud.githubusercontent.com/assets/86978/18890831/78ffcc9e-84c8-11e6-8f45-631a38f6b47a.png)



This is using `Cairo::CairoPNG` for the output:

```R
Cairo::CairoPNG('test-terminal-Cairo.png', width = 600, height = 400)
print(p)
dev.off()
```
![test-terminal-cairo](https://cloud.githubusercontent.com/assets/86978/18890592/620b87c2-84c7-11e6-9ea6-d06c3f9434eb.png)

![test-terminal-cairo](https://cloud.githubusercontent.com/assets/86978/18890834/7f9c2d04-84c8-11e6-97e2-56eae4520684.png)


This is what it looks like in the RStudio viewer pane if I just print it:

```R
p
```
![image](https://cloud.githubusercontent.com/assets/86978/18890765/3171f4ec-84c8-11e6-8e61-dd2f36e31e22.png)

![image](https://cloud.githubusercontent.com/assets/86978/18890863/9eaec94a-84c8-11e6-9001-edf087752254.png)


And this is what it looks like in RStudio if I click on Export->Copy to Clipboard:

![image](https://cloud.githubusercontent.com/assets/86978/18890779/3cb557a4-84c8-11e6-9164-18dd8346ff86.png)

![image](https://cloud.githubusercontent.com/assets/86978/18890876/a99d68c0-84c8-11e6-9085-893342434d70.png)


I suspect the layering of objects has changed, and the different devices treat it differently.


If you're on a Mac and you want to get similar output to my `png()`, I believe you need to run `png(type="cairo")`.

**Comment by thomasp85** [comment]
Thanks - I'll dig into it tomorrow

**Comment by jiho** [comment]
The darker lines are my doing, so that they match the ticks. But the clipping definitely changed. For completeness here is the aspect with 2.1.0 (on left) and current master (on right) on OS X.

<img width="1227" alt="screen shot 2016-09-27 at 23 50 50" src="https://cloud.githubusercontent.com/assets/18445/18893236/41685d56-850d-11e6-8b4c-e95ecf15fe03.png">

The clipping of the sides of the panel was already a bit "too much" in 2.1.0 but not as noticeable because the color was lighter. However, the outline of the facets used to be clipped too. And it was when I tested the color change in #1679 (see the second plot). With the outline not clipped, the aspect is indeed weird. This is also a problem with `theme_classic()`, which has outlines on facet labels.

<img width="612" alt="screen shot 2016-09-27 at 23 54 41" src="https://cloud.githubusercontent.com/assets/18445/18893346/cff88afa-850d-11e6-989a-56209c1e9c8c.png">

**Comment by thomasp85** [comment]
Ok, it's clear that this is my wrongdoing :-)

**Comment by jiho** [comment]
That said, if you could clip the content of the background panel + the grid lines (which need to be clipped of course) but not the outline of the panel or axes, it would make it easier to design themes. For example matching the thickness of the axes with the thickness of the grid lines is difficult/impossible now because axes are clipped and grid lines are not (basically one has to make axes twice as thick and even then, it is not an exact match). It will also help get a smoother, more homogeneous look in various rendering engines. As Winston's examples above show, with rendering engines which favour sharpness (i.e. not OS X's but nearly all others), the clipped lines can appear of different width depending how the rendering engine rounds the number of pixels. Finally, it also makes the outline of facet labels very square (because it is clipped) when one might want a smoother look, with rounded angles.

This would require some tweaking of the themes to keep the current aspect but we could easily do this in concert.

**Comment by thomasp85** [comment]
@wch Can you check out #1789. I did make an error with the new strip constructors so they weren't clipped, but apart from that I could not elicit any change by making stacking and clipping more explicit - I think the panel-border effect is simply an artefact of the new theme settings by @jiho and bad rendering...
