### ISSUE TITLE
Reversed date axis has no breaks, no grid lines

### ISSUE THREAD

**Issue by jennybc** [hadley/ggplot2#956]
I am reversing a data axis by specifying the limits backwards, i.e. giving the larger value first. Perhaps that is the wrong way to reverse a data axis?

In any case, here's a demo of the problem.

```
library(ggplot2)
jDat <- c(      "Date, Holiday",
          "2014-01-01, New Year's Day",
          "2014-02-02, Groundhog Day",
          "2014-07-04, Independence Day",
          "2014-10-31, Halloween",
          "2014-12-31, New Year's Eve")
jDat <- read.csv(textConnection(jDat), colClasses = c(Date = "Date"))
p <- ggplot(jDat, aes(x = 0, y = Date)) + geom_text(aes(label = Holiday), size = 4)
p
p + scale_y_date(limits = c(min(jDat$Date), max(jDat$Date))) # same result as p
```
![good-date-axis](https://cloud.githubusercontent.com/assets/599454/2822518/a0091a10-cf13-11e3-8061-ccba2c2552a6.png)

Now I reverse the y axis.
```
p + scale_y_date(limits = c(max(jDat$Date), min(jDat$Date)))
```
![bad-date-axis](https://cloud.githubusercontent.com/assets/599454/2822520/b0997f50-cf13-11e3-9c26-7ac60691eaf1.png)

**Comment by hhecht** [comment]
Yes, reversed limits don't work in ggplot as they do in base graphics.  The "solution" to this for numbers is to use `scale_y_reverse` or `scale_y_continuous(...trans="reverse")`.  This evidently does not work for dates as the latter complains about trans being defined twice (I assume what happens is that `scale_y_date` decays to a transformed `scale_y_continuous`).  The former fails with ``Error in `-.Date`(x) : unary - is not defined for "Date" objects``, indicating that the function is transforming data, not plot coordinates (which superficially seems like a mistake).

So the bug you've reported is, as I understand it, not actually a bug: it's expected to not work.  Unfortunately, the correct way of doing things also doesn't work.  You might be able to work around this by converting dates to timestamps (seconds since the epoch or similar) and defining your own labels, but I would caution against investing too much time in such a solution with ggplot as reversed axes basically do not work with it: I have a list of a half-dozen bugs I found in my first few hours with ggplot that I will file as soon as I have time.  This will unfortunately be sometime after I redo what I am working on in base graphics, as I have now hit too many dead ends in ggplot, and neither stackoverflow nor my own ingenuity seems able to rescue me.

The above is of course based on my very limited understanding of ggplot, and I write it only because I saw your bug whilst looking for my own and there has been no other response; and I believe it to be correct.  I will be happy to submit to the guidance of anyone who knows better.

**Comment by BrianDiggs** [comment]
There is a related question on StackOverflow: http://stackoverflow.com/q/11053899/892313 and two blog posts I wrote http://ggplot2.tumblr.com/post/25938265813/defining-a-new-transformation-for-ggplot2-scales and http://ggplot2.tumblr.com/post/29433173749/defining-a-new-transformation-for-ggplot2-scales that address how to make a new scale transformation like reversed Date. You can't just string two scales together, you have to make a single encompassing transformation.

**Comment by jennybc** [comment]
Hi @hhecht and @BrianDiggs,

Thanks for your information. This issue is something of a distant memory for me and I am certainly happy if the judgment of you and @hadley is that my problem is one of user error. If that's the case, then just close it. I'm not actively struggling with whatever I was trying to do above.

**Comment by hadley** [comment]
Seems to work now.
